### PR TITLE
Fix issue #85 - weekday graph also shows percentage

### PR DESCRIPTION
**Pull request by cipo7741**
Hi lordi

I added the percentage above the numbers in the weekday chart.
It is implemented checking the cyclic flag - thus another cyclic chart would also show percentages above.
Had to split margin into marginTop and marginBottom.
(Sorry about the whitespace changes.)

Hope you like it. 🛩️ 

Btw - awesome app ;-)

### CODE REVIEW

**Comment by lordi** [comment]
Awesome, Thanks! I'll review and merge it this weekend

**Comment by cipo7741** [comment]
Hi Lordi,

I fixed another issue. Didn't know it would end up in the same merge - but here it is already. 🛸 

So now people could add a SimpleDateFormat string in the Settings. For example dd-MM-yyyy
It does also allow time and number of week which is of limited use.

Hope you like this as well.

**Comment by lordi** [comment]
Nice, I tested both changes and they work great.

Only one thing, maybe we can show a more descriptive subtitle here:

image

Something like "Override system date format (e.g. mm-DD-yyyy)" and remove the hint in the input box?

**Comment by lordi** [comment]
Because the hint does not show if the user entered "" as a dateformat. Entering an empty string as a date format should restore the original behaviour, this also does not seem to be the case rn

**Comment by cipo7741** [comment]
sounds good

**Comment by cipo7741** [comment]
Sorry - just saw that I commited with the wrong commit mail. I'll fix the commits later and make a new merge request.
Not sure I can fix it right now (not used to rebases) - so maybe tomorrow.

**Pull request closed without merging**
