### PR TITLE
Issue 131 fix backups

### PR DESCRIPTION
**Pull request by 0xDB**
Hi!

I ran into the problem of db export/import on Android 11 and fixed it. There was already an open issue (#131) regarding this. I'm rather new to Android development, constructive criticism is always welcome.

On a sidenote, Android Studio Lint complains about many things unrelated to this issue/fix, one of them is the outdated target API/SDK level. If you can't publish a new version with the bugfix on the Play Store please send me a message, I might look into fixing it when I have the time.

Cheers,
Daniel

### CODE REVIEW

**Comment by lordi** [comment]
Thanks at first glance it looks good, will look more into it this weekend

**Comment by lordi** [comment]
Would you be interested to be a co-maintainer on this repo? My last commit is 2 years ago and currently I don't even have an up-to-date development env.

**Comment by 0xDB** [comment]
Sure! I'm currently trying to improve my Android dev-skills, might as well work on improving this app in the process :)

**Comment by 0xDB** [comment]
I fixed the Lint errors best I could, can't do the translations without google translate though. Feel free to cherry-pick from the commits. It would be great if you could publish an updated version with the backup-fix on google play!

**Comment by lordi** [comment]
Awesome! I'll take a look later and add you as a maintainer. We should be able to get an updated version in Play store in the short term.

**Comment by lordi** [comment]
I just installed Androd Studio and successfully compiled your branch. I will merge it and bump a new version.

**Comment by duelafn** [comment]
Woo hoo! Thanks all!

**Pull request merged**
