### PR TITLE
Fixes for Android API 35

### PR DESCRIPTION
**Pull request by flyingOwl**
Increase target SDK to 35 so it will run on current versions of Android.

One commit fixes the crash when changing the color and icon of a track (see #162 and #157). Another commit adds working notifications for Android 13+ which needs a requestPermissions() call.

Note: This is just a quick fix to put the app in a working state again. A lot of stuff in the code is deprecated and needs a proper refactoring.

### CODE REVIEW

**Comment by lordi** [comment]
Hi, thanks for the PR! For merging I think the unit tests would need to run which are currently failing. Would it be possible for you to check these?

Do you use Tickmate via Play store or F-Droid?

**Comment by flyingOwl** [comment]
I tried to run Tickmate from F-Droid but I experienced the same crashes when changing the icon or the color of a track as others.

I will check the unit tests!

**Comment by flyingOwl** [comment]
The unit tests were failing due to outdated dependencies. That should be fixed now.

**Comment by lordi** [comment]
Thanks. If I find the time I'll look into releasing a new version this weekend

**Pull request merged**
